# Generated by Django 5.0.7 on 2024-07-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_product_id_alter_cartmodel_user'),
        ('products', '0004_remove_productmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.productmodel'),
        ),
    ]
