# Generated by Django 5.0.7 on 2024-07-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='user_id',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table=None,
        ),
    ]
