# Generated by Django 5.0.7 on 2024-07-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='user',
        ),
    ]
